CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_video" varchar NOT NULL,
  "course_id" int NOT NULL,
  "url" varchar NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title_course" varchar UNIQUE NOT NULL,
  "description" text NOT NULL,
  "level" varchar NOT NULL,
  "user_id" int NOT NULL,
  "category_id" int NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "qualifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar NOT NULL,
  "description" varchar NOT NULL
);

CREATE TABLE "qualifications_users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "qualification_id" int,
  "user_id" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "qualifications_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "qualifications_users" ADD FOREIGN KEY ("qualification_id") REFERENCES "qualifications" ("id");

//CREANDO 2 REGISTROS PARA CADA TABLA 
----------------------------------------------------------------
//TABLA USUARIOS 
//CR_EATE
insert into users (
	user_name,
	email,
	"password" ,
	age 
) values (
	'yess',
	'yessica@academlo.com',
	'root',
	20
), (
	'Juanca',
	'juan@aoutlook.com',
	'adm',
	27
), (
	'Zoe',
	'Marian@gmail.com',
	'chil',
	4
);

select * from users;

//UP_DATE
update users set user_name = 'juanca' where id = 2;
update users set email = 'marian@kinder.com' where id = 3;

//DE_LETE
delete from users where id = 1;
------------------------------------------------------------------------
//TABLA CATEGORIAS
insert into categories (
	category_name
) values (
	'backend'
),(
	'frontend'
),(
	'redes'
);

select * from categories;

//UP_DATE
update categories set category_name = 'Backend Programming' where id = 1;
update categories set category_name = 'Frontend Programming' where id = 2;
update categories set category_name = 'Networks and Security' where id = 3;

//DE_LETE
delete from categories where id = 3;

------------------------------------------------------------------------
//TABLA CURSOS 
//Backend
insert into courses (
	title_course,
	description ,
	"level" ,
	user_id,
	category_id,
	teacher
) values (
	'Node js',
	'it is a course based on the js lengaje',
	'medium',
	2,
	1,
	'Sahid Kick'
), (
	'Jave',
	'it is a course based on the JDK',
	'beginner',
	3,
	1,
	'Roel Veliz'
),(
	'Python',
	'it is a course based in machine learning',
	'dificultoso',
	2,
	1,
	'Erick Perez'
);

select * from courses;
//UP_DATE
update courses set description = 'it is a course based on the js language' where id = 1;
update courses set title_course  = 'Java' where id = 2;
update courses set level  = 'Dificult' where id = 3;

//DE_LETE
delete from courses where id = 2;
 
//Frontend 
insert into courses (
	title_course,
	description ,
	"level" ,
	user_id,
	category_id,
	teacher
) values (
	'React',
	'it is a course based on redux and toolkit',
	'medium',
	2,
	2,
	'Andres Mendoza'
), (
	'Html and Css',
	'it is a course based on the styles for landing page',
	'beginner',
	3,
	2,
	'Brenda Gonzales'
),(
	'Javascript',
	'it is a course based in code native',
	'medium',
	2,
	2,
	'Ian Rosas'
);

select * from courses;

----------------------------------------------------------------------
//TABLA VIDEO_CURSOS
insert into course_video (
	title_video,
	course_id ,
	url 
) values (
	'Learning node js',
	1,
	'https://www.youtube.com/watch?v=1hpc70_OoAg'
), (
	'Programming with python',
	3,
	'https://www.youtube.com/watch?v=1hpc70_OoAg'
),(
	'Projects for react',
	4,
	'https://www.youtube.com/watch?v=4V7rfombLkc'
),(
	'Improve your skills for job',
	5,
	'https://www.youtube.com/watch?v=4V7rfombLkc'
),(
	'The three best books of js',
	6,
	'https://www.youtube.com/watch?v=CpelevzT8xg'
);

select * from course_video;

--------------------------------------------------------------------------------
//TABLA CALIFICACIONES 
//CRE_ATE
insert into qualifications (
	status,
	description 
) values (
	'A',
	'approved course'
), (
	'D',
	'deprecated course'
);

//UP_DATE
update qualifications set status = 'Approved' where id = 1;
update qualifications set status = 'Deprecated' where id = 2;

update qualifications set description  = 'satisfactorily approved course' where id = 1;
update qualifications set description  = 'failded course' where id = 2;

select * from qualifications;
--------------------------------------------------------------------------
//TABLA USUARIOS_CALIFICACIONES
insert into qualifications_users (
	qualification_id,
	user_id
) values (
	1,
	2
), (
	2,
	3
);


select * from qualifications_users;

//CONSULTAS 
//Mostrar un usuario con un curso y su categorìa
select user_name, title_course , description ,"level",teacher, category_name
from users 
join courses on courses.user_id = users.id 
join categories on categories.id = category_id 
where courses.user_id = 3;

//Mostrar usuarios aprobados 
select user_name, status, description
from users 
join qualifications_users on qualifications_users.user_id = user_id 
join qualifications on qualifications.id = qualification_id 
where qualifications_users.user_id = 2;